#!/bin/bash

STDIN_FILE=$1

# emit additional http response headers
#echo "server: premortal/cit-384/ml855063"
#echo "date: $(date)"

if [[ -f $STDIN_FILE ]] ; then
    # cat file but do some substitutions
        # substitute "status:" with "HTTP/1.1"
        # add additional response headers before the blank line
    cat "$STDIN_FILE" #| sed -e 's/status:/HTTP/\1.1'
    #sed '/^ /a server: premortal/cit-384/ml855063'
else
    echo "HTTP/1.1 404 File Not Found"
    echo "server: premortal/cit-384/ml855063"
    echo "date: $(date)"
fi

